config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout' }

  resources :categories

  get  'dashboard', to: 'welcome#dashboard'

  root 'welcome#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  enum color: %w[indigo purple pink red orange yellow green lime teal cyan azure gray gray-dark]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false }

  validates :currency, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include CustomDeviseAttributes
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'dashboard'

  # GET /categories
  def index
    @categories = current_user.categories
  end

  def show
  end

  # GET /categories/new
  def new
    @form = CategoryForm.new(Category.new)
  end

  # POST /categories
  def create
    @form = CategoryForm.new(Category.new)

    if @form.validate(params[:category])
      @form.save_with_user(current_user)
      redirect_to categories_path, notice: "Category '#{@form.name}' has been created"
    else
      render :new
    end
  end

  # GET /categories/:id/edit
  def edit
    @form = CategoryForm.new(set_category)
  end

  # PATCH /categories/:id
  def update
    @form = CategoryForm.new(set_category)

    if @form.validate(params[:category])
      @form.save
      redirect_to categories_path, notice: "Category '#{@form.name}' has been updated"
    else
      render :edit
    end
  end

  # DELETE /categories/:id
  def destroy
    # TODO: Service to delete category and move bills to Default Category
    category = set_category
    category.destroy

    redirect_to categories_path, notice: "Category '#{category.name}' has been deleted"
  end

  private

  def set_category
    current_user.categories.find(params[:id])
  end

end

app/controllers/concerns/custom_devise_attributes.rb
module CustomDeviseAttributes
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: custom_attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: custom_attributes)
  end

  def custom_attributes
    %i[username first_name last_name currency]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  layout :set_layout

  def home
  end

  def dashboard
  end

  private

  def set_layout
    action_name == 'home' ? 'application' : 'dashboard'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_card.html.erb
  <div class="col-md-6 col-xl-4">
    <div class="card">
      <div class="card-status bg-<%= category.color %>"></div>

      <div class="card-header">
        <h3 class="card-title"><%= category.name %></h3>

        <div class="card-options">
          <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
        </div>
      </div>

      <div class="card-body">
        <span class="category-sum">13.80 <%= user.currency %></span>
        <p class="category-text">It is</p>
        <span class="category-percent">34.5 %</span>
        <p class="category-text">as against to last month.</p>

        <!-- TO DELETE -->
        <div class="dev-helper">
          <%=  %>
        </div>
      </div>

      <div class="card-footer text-center">
        <%= link_to 'Details', category_path(category), class: 'btn btn-secondary' %>

        <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-secondary' %>

        <%= link_to 'Delete', category_path(category), class: 'btn btn-danger', method: :delete,
                    data: { title: 'Delete Category', confirm: 'Are you sure?', commit: 'Delete' } %>
      </div>
    </div>
  </div>

app/views/categories/_form.html.erb
  <%= simple_form_for @form do |f| %>
    <div class="form-group">
      <%= f.input :name, autofocus: 'on', placeholder: 'Food' %>
    </div>

    <div class="form-group">
      <%= f.label :color %>

      <div class="row gutters-xs">
        <% Category.colors.each_key do |color| %>
        <div class="col-auto">
          <label class="colorinput">
            <%= f.radio_button :color, color, class: 'colorinput-input' %>
            <span class="colorinput-color bg-<%= color %>"></span>
          </label>
        </div>
        <% end %>
      </div>
    </div>

    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>

app/views/categories/edit.html.erb
<div class="my-3 my-md-5">
  <div class="container">
      <div class="row">

        <div class="col-md-12">
          <div class="card">

            <div class="card-header">
              <h3 class="card-title">Edit category</h3>
            </div>

            <div class="card-body">
              <div class="row">

                <div class="col-md-6">
                  <%= render 'categories/form' %>
                </div>

                <div class="col-md-6">
                  <div class="dev-helper">
                    <%= @form.inspect %>
                  </div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>

              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>

app/views/categories/index.html.erb
  <div class="my-3 my-md-5">
    <div class="container">
        <div class="row">
          <% if @categories.present? %>

          <% @categories.each do |category| %>
            <%= render 'categories/card', category: category, user: current_user %>
          <% end %>

          <% else %>

          <div class="col-md-12">
            <div class="card">
              <div class="card-body">
                <p>Sorry, there are no categories yet. Let's create the first one!</p>
                <%= link_to new_category_path, class: 'btn btn-success' do %>
                  <i class="fe fe-plus-circle"></i> New category
                <% end %>
              </div>
            </div>
          </div>

          <% end %>
        </div>
      </div>
    </div>

app/views/categories/new.html.erb
<div class="my-3 my-md-5">
  <div class="container">
      <div class="row">

        <div class="col-md-12">
          <div class="card">

            <div class="card-header">
              <h3 class="card-title">New category</h3>
            </div>

            <div class="card-body">
              <div class="row">

                <div class="col-md-6">
                  <%= render 'categories/form' %>
                </div>

                <div class="col-md-6">
                  <div class="dev-helper">
                    <%= @form.inspect %>
                  </div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>

              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">

      <%= yield %>

      <%= render 'shared/flashes' unless flash.empty? %>

    </div>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="page">
      <div class="page-main">
        <%= render 'shared/header' %>

        <%= yield %>

        <%= render 'shared/flashes' unless flash.empty? %>
      </div>

      <!-- <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p> -->


    </div>
  </body>
</html>

app/views/shared/_flashes.html.erb
<div id="snackbar">
  <% flash.each do |key, value| %>
    <%= content_tag(:span, value, class: "flash flash-#{key}") %>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="header py-4">
	<div class="container">
		<div class="d-flex">
      <%= link_to 'Billy', dashboard_path, class: 'header-brand' %>

      <div class="d-flex order-lg-2 ml-auto">
        <div class="dropdown">
					<a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
						<span class="avatar" style="background-color: gray"></span>
						<span class="ml-2 d-none d-lg-block">
							<span class="text-default"><%= current_user ? current_user.username : 'Guest' %></span>
							<small class="text-muted d-block mt-1">User</small>
						</span>
					</a>
					<div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">

            <%= link_to edit_user_registration_path, class: 'dropdown-item' do %>
              <i class="dropdown-icon fe fe-user"></i> Profile
            <% end %>

						<div class="dropdown-divider"></div>

						<a class="dropdown-item" href="#">
							<i class="dropdown-icon fe fe-help-circle"></i> Need help?
						</a>

            <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
              <i class="dropdown-icon fe fe-log-out"></i> Log out
            <% end %>
					</div>
				</div>
      </div>

      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
				<span class="header-toggler-icon"></span>
			</a>

    </div>
  </div>
</div>

<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
	<div class="container">
		<div class="row align-items-center">
			<div class="col-lg-3 ml-auto">
				<form class="input-icon my-3 my-lg-0">
					<input type="search" class="form-control header-search" placeholder="Search&hellip;" tabindex="1">
					<div class="input-icon-addon">
						<i class="fe fe-search"></i>
					</div>
				</form>
			</div>
			<div class="col-lg order-lg-first">
				<%= render 'shared/menu' %>
			</div>
		</div>
	</div>
</div>

app/views/shared/_menu.html.erb
<ul class="nav nav-tabs border-0 flex-column flex-lg-row">

  <li class="nav-item">
    <%= link_to dashboard_path, class: 'nav-link' do %>
      <i class="fe fe-home"></i> Home
    <% end %>
  </li>

  <li class="nav-item">
    <a href="javascript:void(0)" class="nav-link active" data-toggle="dropdown"><i class="fe fe-calendar"></i> Categories</a>
    <div class="dropdown-menu dropdown-menu-arrow">

      <%= link_to categories_path, class: 'dropdown-item' do %>
        <i class="dropdown-icon fe fe-list"></i> Show all
      <% end %>

      <%= link_to new_category_path, class: 'dropdown-item' do %>
        <i class="dropdown-icon fe fe-plus-circle"></i> Add new
      <% end %>

    </div>
  </li>

  <li class="nav-item">
    <a href="#" class="nav-link">
      <i class="fe fe-file"></i> Shops
    </a>
  </li>
</ul>

app/views/welcome/dashboard.html.erb
<h1>Hello from Test!</h1>

app/views/welcome/home.html.erb
<div class="page-single">

  <div class="container">
		<div class="row">
			<div class="col col-login mx-auto">
				<div class="text-center mb-8">
          <h2>Billy</h2>
          <h4>Lorem ipsum dolor sit amet farit pramo alcedi tranko.</h4>
				</div>

        <div class="acion-buttons">
          <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-secondary btn-block' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-block' %>
        </div>
      </div>
    </div>
  </div>
</div>